Last login: Wed Oct 19 19:49:46 on ttys007
(base) mac@MACs-MacBook-Pro django-project % code .
(base) mac@MACs-MacBook-Pro django-project % ssh api.testoin.com
mac@api.testoin.com: Permission denied (publickey).
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.com
Linux instance-1 5.10.0-18-cloud-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Oct 17 12:15:34 2022 from 117.96.169.89
siddythings73@instance-1:~$ cd django-project/
siddythings73@instance-1:~/django-project$ nano application/settings.py 
siddythings73@instance-1:~/django-project$ sudo systemctl restart emperor.uwsgi.service
siddythings73@instance-1:~/django-project$ nano application/settings.py 
siddythings73@instance-1:~/django-project$ exit
logout
Connection to api.testoin.com closed.
(base) mac@MACs-MacBook-Pro django-project % git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   crm_labs/rest_views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	crm_labs/services.py
	siddythings73_firebase_key.json
	utilities/services.py

no changes added to commit (use "git add" and/or "git commit -a")
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.com
Linux instance-1 5.10.0-18-cloud-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Oct 23 13:38:46 2022 from 223.225.120.49
siddythings73@instance-1:~$ cd django-project/
siddythings73@instance-1:~/django-project$ nano application/settings.py 
siddythings73@instance-1:~/django-project$ sudo systemctl restart emperor.uwsgi.service
siddythings73@instance-1:~/django-project$ source ../venv/bin/activate
(venv) siddythings73@instance-1:~/django-project$ ./manage.py runserver 9001
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 23, 2022 - 14:13:39
Django version 4.1.1, using settings 'application.settings'
Starting development server at http://127.0.0.1:9001/
Quit the server with CONTROL-C.
client_loop: send disconnect: Broken pipe
(base) mac@MACs-MacBook-Pro django-project % git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   crm_labs/rest_views.py
	modified:   webapp/views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	crm_labs/services.py
	siddythings73_firebase_key.json
	utilities/services.py

no changes added to commit (use "git add" and/or "git commit -a")
(base) mac@MACs-MacBook-Pro django-project % git add .
(base) mac@MACs-MacBook-Pro django-project % git status            
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   crm_labs/rest_views.py
	modified:   webapp/views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	crm_labs/services.py
	siddythings73_firebase_key.json
	utilities/services.py

no changes added to commit (use "git add" and/or "git commit -a")
(base) mac@MACs-MacBook-Pro django-project % git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore
	modified:   crm_labs/rest_views.py
	modified:   webapp/views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	crm_labs/services.py
	utilities/services.py

no changes added to commit (use "git add" and/or "git commit -a")
(base) mac@MACs-MacBook-Pro django-project % git add .
(base) mac@MACs-MacBook-Pro django-project % git commit -m "update packages"
[main 0263374] update packages
 5 files changed, 43 insertions(+), 13 deletions(-)
 create mode 100644 crm_labs/services.py
 create mode 100644 utilities/services.py
(base) mac@MACs-MacBook-Pro django-project % git push origin main
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.37 KiB | 1.38 MiB/s, done.
Total 9 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/siddythings/testoin-project.git
To https://github.com/siddythings/django-project.git
   02a0431..0263374  main -> main
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.com
Linux instance-1 5.10.0-18-cloud-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Oct 23 13:55:33 2022 from 223.225.120.49
siddythings73@instance-1:~$ cd django-project/
siddythings73@instance-1:~/django-project$ git pull origin main
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), 1.36 KiB | 86.00 KiB/s, done.
From https://github.com/siddythings/django-project
 * branch            main       -> FETCH_HEAD
   02a0431..0263374  main       -> origin/main
Updating 02a0431..0263374
Fast-forward
 .gitignore             |  3 +--
 crm_labs/rest_views.py | 22 ++++++++++++----------
 crm_labs/services.py   | 25 +++++++++++++++++++++++++
 utilities/services.py  |  0
 webapp/views.py        |  6 +++++-
 5 files changed, 43 insertions(+), 13 deletions(-)
 create mode 100644 crm_labs/services.py
 create mode 100644 utilities/services.py
siddythings73@instance-1:~/django-project$ source ../venv/bin/activate
(venv) siddythings73@instance-1:~/django-project$ ./manage.py runserver 9001
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/siddythings73/django-project/application/urls.py", line 25, in <module>
    path("lab/", include("crm_labs.rest_urls")),
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/siddythings73/django-project/crm_labs/rest_urls.py", line 3, in <module>
    from crm_labs import rest_views
  File "/home/siddythings73/django-project/crm_labs/rest_views.py", line 10, in <module>
    from crm_labs.services import BookingServices
  File "/home/siddythings73/django-project/crm_labs/services.py", line 1, in <module>
    import firebase_admin, requests
ModuleNotFoundError: No module named 'firebase_admin'
^C(venv) siddythings73@instance-1:~/django-project$ pip install firebase-admin==5.0.2
Collecting firebase-admin==5.0.2
  Downloading firebase_admin-5.0.2-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.3/113.3 kB 3.4 MB/s eta 0:00:00
Collecting google-api-python-client>=1.7.8
  Downloading google_api_python_client-2.65.0-py2.py3-none-any.whl (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 42.1 MB/s eta 0:00:00
Collecting cachecontrol>=0.12.6
  Downloading CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)
Collecting google-api-core[grpc]<2.0.0dev,>=1.22.1
  Downloading google_api_core-1.33.2-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.5/115.5 kB 17.6 MB/s eta 0:00:00
Collecting google-cloud-firestore>=2.1.0
  Downloading google_cloud_firestore-2.7.2-py2.py3-none-any.whl (253 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.3/253.3 kB 27.5 MB/s eta 0:00:00
Collecting google-cloud-storage>=1.37.1
  Downloading google_cloud_storage-2.5.0-py2.py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 15.4 MB/s eta 0:00:00
Requirement already satisfied: requests in /home/siddythings73/venv/lib/python3.9/site-packages (from cachecontrol>=0.12.6->firebase-admin==5.0.2) (2.28.1)
Collecting msgpack>=0.5.2
  Downloading msgpack-1.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 kB 39.0 MB/s eta 0:00:00
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5
  Downloading protobuf-3.20.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 47.8 MB/s eta 0:00:00
Collecting google-auth<3.0dev,>=1.25.0
  Downloading google_auth-2.13.0-py2.py3-none-any.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.5/174.5 kB 23.2 MB/s eta 0:00:00
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Downloading googleapis_common_protos-1.56.4-py2.py3-none-any.whl (211 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.7/211.7 kB 26.3 MB/s eta 0:00:00
Collecting grpcio-status<2.0dev,>=1.33.2
  Downloading grpcio_status-1.50.0-py3-none-any.whl (14 kB)
Collecting grpcio<2.0dev,>=1.33.2
  Downloading grpcio-1.50.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 55.9 MB/s eta 0:00:00
Collecting httplib2<1dev,>=0.15.0
  Downloading httplib2-0.20.4-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 15.3 MB/s eta 0:00:00
Collecting uritemplate<5,>=3.0.1
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting google-auth-httplib2>=0.1.0
  Downloading google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting google-cloud-core<3.0.0dev,>=1.4.1
  Downloading google_cloud_core-2.3.2-py2.py3-none-any.whl (29 kB)
Collecting proto-plus<2.0.0dev,>=1.22.0
  Downloading proto_plus-1.22.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 kB 7.6 MB/s eta 0:00:00
Collecting google-resumable-media>=2.3.2
  Downloading google_resumable_media-2.4.0-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 11.3 MB/s eta 0:00:00
Requirement already satisfied: six>=1.9.0 in /home/siddythings73/venv/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<2.0.0dev,>=1.22.1->firebase-admin==5.0.2) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/siddythings73/venv/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<2.0.0dev,>=1.22.1->firebase-admin==5.0.2) (4.9)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 18.8 MB/s eta 0:00:00
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32 kB)
Collecting grpcio-status<2.0dev,>=1.33.2
  Downloading grpcio_status-1.49.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.48.2-py3-none-any.whl (14 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 14.7 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /home/siddythings73/venv/lib/python3.9/site-packages (from requests->cachecontrol>=0.12.6->firebase-admin==5.0.2) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/siddythings73/venv/lib/python3.9/site-packages (from requests->cachecontrol>=0.12.6->firebase-admin==5.0.2) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/siddythings73/venv/lib/python3.9/site-packages (from requests->cachecontrol>=0.12.6->firebase-admin==5.0.2) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/siddythings73/venv/lib/python3.9/site-packages (from requests->cachecontrol>=0.12.6->firebase-admin==5.0.2) (1.26.12)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/siddythings73/venv/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<2.0.0dev,>=1.22.1->firebase-admin==5.0.2) (0.4.8)
Installing collected packages: msgpack, uritemplate, pyparsing, pyasn1-modules, protobuf, grpcio, google-crc32c, cachetools, proto-plus, httplib2, googleapis-common-protos, google-resumable-media, google-auth, cachecontrol, grpcio-status, google-auth-httplib2, google-api-core, google-cloud-core, google-api-python-client, google-cloud-storage, google-cloud-firestore, firebase-admin
Successfully installed cachecontrol-0.12.11 cachetools-5.2.0 firebase-admin-5.0.2 google-api-core-1.33.2 google-api-python-client-2.65.0 google-auth-2.13.0 google-auth-httplib2-0.1.0 google-cloud-core-2.3.2 google-cloud-firestore-2.7.2 google-cloud-storage-2.5.0 google-crc32c-1.5.0 google-resumable-media-2.4.0 googleapis-common-protos-1.56.4 grpcio-1.50.0 grpcio-status-1.48.2 httplib2-0.20.4 msgpack-1.0.4 proto-plus-1.22.1 protobuf-3.20.3 pyasn1-modules-0.2.8 pyparsing-3.0.9 uritemplate-4.1.1

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
(venv) siddythings73@instance-1:~/django-project$ ./manage.py runserver 9001
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/siddythings73/django-project/application/urls.py", line 25, in <module>
    path("lab/", include("crm_labs.rest_urls")),
  File "/home/siddythings73/venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/siddythings73/django-project/crm_labs/rest_urls.py", line 3, in <module>
    from crm_labs import rest_views
  File "/home/siddythings73/django-project/crm_labs/rest_views.py", line 10, in <module>
    from crm_labs.services import BookingServices
  File "/home/siddythings73/django-project/crm_labs/services.py", line 3, in <module>
    from application.settings import FIREBASE_NOTIFICATION_KEY, NOTIFICATION_STORAGE_BUKET
ImportError: cannot import name 'FIREBASE_NOTIFICATION_KEY' from 'application.settings' (/home/siddythings73/django-project/application/settings.py)
^C(venv) siddythings73@instance-1:~/django-project$ nano application/settings.py 
(venv) siddythings73@instance-1:~/django-project$ nano siddythings73_firebase_key.json
(venv) siddythings73@instance-1:~/django-project$ ls
'=3.0.0'           crm         myproject.sock        siddythings73_firebase_key.json   users          webapp
 application       crm_labs    myproject_uwsgi.ini   static                            utilities
 authentications   manage.py   requrements.txt       templates                         uwsgi_params
(venv) siddythings73@instance-1:~/django-project$ ./manage.py runserver 9001
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 26, 2022 - 03:30:11
Django version 4.1.1, using settings 'application.settings'
Starting development server at http://127.0.0.1:9001/
Quit the server with CONTROL-C.
^C(venv) siddythings73@instance-1:~/django-project$ sudo systemctl restart emperor.uwsgi.service
(venv) siddythings73@instance-1:~/django-project$ client_loop: send disconnect: Broken pipe
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.com
^C
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.in 
The authenticity of host 'api.testoin.in (35.188.37.141)' can't be established.
ED25519 key fingerprint is SHA256:Jn/vZK19gec6Vnet5sy7Za6iGL+YzRsCQuTBF8dlUXo.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:51: 35.188.37.141
    ~/.ssh/known_hosts:54: api.testoin.com
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'api.testoin.in' (ED25519) to the list of known hosts.
Linux instance-1 5.10.0-18-cloud-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Oct 26 03:26:29 2022 from 106.205.45.61
siddythings73@instance-1:~$ exit
logout
Connection to api.testoin.in closed.
(base) mac@MACs-MacBook-Pro django-project % ssh siddythings73@api.testoin.in
Linux instance-1 5.10.0-18-cloud-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Oct 30 05:05:00 2022 from 106.195.56.16
siddythings73@instance-1:~$ nano /etc/nginx/sites-enabled/myproject.conf 


Use "fg" to return to nano.

[1]+  Stopped                 nano /etc/nginx/sites-enabled/myproject.conf
siddythings73@instance-1:~$ sudo nano /etc/nginx/sites-enabled/myproject.conf 
siddythings73@instance-1:~$ sudo systemctl restart emperor.uwsgi.service
siddythings73@instance-1:~$ sudo certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which names would you like to activate HTTPS for?
We recommend selecting either all domains, or all domains in a VirtualHost/server block.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: api.testoin.com
2: api.testoin.in
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 2
Requesting a certificate for api.testoin.in

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/api.testoin.in/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/api.testoin.in/privkey.pem
This certificate expires on 2023-01-28.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.

Deploying certificate
Successfully deployed certificate for api.testoin.in to /etc/nginx/sites-enabled/myproject.conf
Congratulations! You have successfully enabled HTTPS on https://api.testoin.in

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
siddythings73@instance-1:~$ exit
logout
There are stopped jobs.
siddythings73@instance-1:~$ exit
logout
Received SIGHUP or SIGTERM
(venv) siddythings73@instance-1:~/django-project$ ls
'=3.0.0'       authentications   crm_labs    myproject.sock        requrements.txt                   static      users       uwsgi_params
 application   crm               manage.py   myproject_uwsgi.ini   siddythings73_firebase_key.json   templates   utilities   webapp
(venv) siddythings73@instance-1:~/django-project$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   requrements.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	=3.0.0
	myproject_uwsgi.ini
	uwsgi_params

(venv) siddythings73@instance-1:~/django-project$ git add myproject_uwsgi.ini
(venv) siddythings73@instance-1:~/django-project$ git add uwsgi_params
(venv) siddythings73@instance-1:~/django-project$ git commit -m "update req"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <siddythings73@instance-1.us-central1-a.c.healthlab-363904.internal>) not allowed
(venv) siddythings73@instance-1:~/django-project$ nano requrements.txt 

  GNU nano 5.4                                                                                    requrements.txt                                                                                             
proto-plus==1.22.1
protobuf==3.20.3
psycopg2-binary==2.9.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodome==3.15.0
pyHanko==0.14.0
pyhanko-certvalidator==0.19.5
pymongo==4.2.0
pyparsing==3.0.9
PyPDF3==1.0.6
pyrsistent==0.18.1
python-bidi==0.4.2
python-dateutil==2.8.2
python-jose==3.3.0
pytz==2022.2.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
qrcode==7.3.1
reportlab==3.6.11
requests==2.28.1
rsa==4.9
s3transfer==0.6.0
six==1.16.0
sqlparse==0.4.3
svglib==1.4.1
tinycss2==1.1.1
tqdm==4.64.1
tzdata==2022.4
tzlocal==4.2
uritemplate==4.1.1
uritools==4.0.0
urllib3==1.26.12
uWSGI==2.0.20
webencodings==0.5.1
xhtml2pdf==0.2.8

